apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-{{ .Values.lookup }}-monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-dashboard.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
