apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lookup }}
  labels:
    {{- include "k8s-dashboard.labels" . | nindent 4 }}
  {{- if and .Values.service.hostname .Values.service.domain }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ printf "%s.%s.k8s." .Values.service.hostname .Values.service.domain }}
    {{- if .Values.service.lbipam }}
    lbipam.cilium.io/ips: "{{ .Values.service.lbipam }}"
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.service.hostname .Values.service.domain }}
  type: LoadBalancer
  externalTrafficPolicy: Local
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-dashboard.selectorLabels" . | nindent 4 }}
